spring:
  cloud:
    gateway:
      locator:
        enabled: true

security:
  encode:
    # 前端密码密钥，必须16位
    key: 'smartsmartsmart1'

# 不校验验证码终端
ignore:
  clients:
    - test
  swagger-providers:
    - smart-auth
    - smart-tx-manager
