## spring security 配置
security:
  oauth2:
    client:
      client-id: ENC(z3eZkekNAXSc5sdF1GLXWQ==)
      client-secret: ENC(z3eZkekNAXSc5sdF1GLXWQ==)
      scope: server
      ignore-urls:
        - '/actuator/**'
        - '/v2/api-docs'
        - '/service/**'
        - '/editor-app/**'
        - '/task/view/*'
        - '/process/resource/**'
        - '/modeler.html'
spring:
  autoconfigure:
    exclude: org.activiti.spring.boot.SecurityAutoConfiguration
  activiti:
    check-process-definitions: false
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://smart-mysql:3306/smart_ac?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2B8&nullCatalogMeansCurrent=true
# swagger相关配置,覆盖全局配置
swagger:
  authorization:
    authorization-scope-list:
      - scope: 'server'
        description: 'server all'
      - scope: 'read'
        description: 'read all'
      - scope: 'write'
        description: 'access all'
# Logger Config
